Perfect division applied for fee distribution
ommfinance/openmoneymarket-contracts pull request #211
Opened 2023-12-19 15:46 UTC by Anurupa03

2023-12-20 18:33 UTC, goldworm-icon requested changes

2023-12-20 18:33 UTC, goldworm-icon commented on core-contracts/FeeDistribution/src/main/java/finance/omm/score/fee/distribution/AbstractFeeDistribution.java
> +            BigInteger amountToDistribute = (percentageToDistribute.multiply(remaining)).divide(denominator);
Zero denominator can raise "java.lang.ArithmeticException: BigInteger divide by zero".

2023-12-20 18:33 UTC, goldworm-icon commented on core-contracts/FeeDistribution/src/main/java/finance/omm/score/fee/distribution/AbstractFeeDistribution.java
>      protected void distributeFee(BigInteger amount) {
```suggestion
    protected void distributeFee(BigInteger amount) {
        if (amount.signum() <= 0) {
            return;
        }
```

2023-12-20 18:33 UTC, goldworm-icon commented on core-contracts/FeeDistribution/src/main/java/finance/omm/score/fee/distribution/AbstractFeeDistribution.java
> +            BigInteger amountToDistribute = (percentageToDistribute.multiply(remaining)).divide(denominator);
I left my suggestion on the following issue:
https://github.com/ommfinance/openmoneymarket-audit/issues/16#issuecomment-1864943798

2023-12-29 02:30 UTC, goldworm-icon approved these changes

2024-01-02 09:44 UTC, Suyog007 approved these changes
Looks Good.

2024-01-02 09:45 UTC, merged